# Generated by Django 2.0 on 2019-08-08 12:46

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateField(default=datetime.datetime.now)),
                ('end_dt', models.DateField(default=datetime.datetime.now)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Foods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludeMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateField(default=datetime.datetime.now)),
                ('end_dt', models.DateField(default=datetime.datetime.now)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='main', max_length=20)),
                ('standalone', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Foods')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_flg', models.BooleanField(default=False)),
                ('meal', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=10)),
                ('uses', models.IntegerField(default=0)),
                ('amt_arr', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None)),
                ('food', models.ForeignKey(on_delete='CASCADE', related_name='fd_fav', to='food.Foods')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], max_length=10)),
                ('dish_num', models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='Whole Meal', max_length=20)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Foods')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTagPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], max_length=10)),
                ('dish_num', models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='Whole Meal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProbRejectFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_r', models.DecimalField(decimal_places=4, default=0.85, max_digits=5)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_pref_food', to='food.Foods')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProbRejectMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_r', models.DecimalField(decimal_places=4, default=0.85, max_digits=5)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_pref_meal', to='plan.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], max_length=10)),
                ('dish_num', models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='Whole Meal', max_length=20)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealTagPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], max_length=10)),
                ('dish_num', models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='Whole Meal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrefMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_flg', models.BooleanField(default=False)),
                ('menu_name', models.CharField(max_length=300, null=True)),
                ('reusable_flg', models.BooleanField(default=False)),
                ('public_flg', models.BooleanField(default=False)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], default='Any', max_length=10)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cal_adj', models.IntegerField(null=True)),
                ('bmr', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('activity_lvl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tdee', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('cal_req', models.DecimalField(decimal_places=2, default=2000, max_digits=7)),
                ('age_update_dt', models.DateField(null=True)),
                ('multi_planner_flg', models.BooleanField(default=False)),
                ('prot_bool', models.BooleanField(default=True)),
                ('carb_bool', models.BooleanField(default=True)),
                ('fat_bool', models.BooleanField(default=True)),
                ('stf_bool', models.BooleanField(default=False)),
                ('fib_bool', models.BooleanField(default=False)),
                ('sug_bool', models.BooleanField(default=False)),
                ('sod_bool', models.BooleanField(default=False)),
                ('cho_bool', models.BooleanField(default=False)),
                ('clc_bool', models.BooleanField(default=False)),
                ('irn_bool', models.BooleanField(default=False)),
                ('vta_bool', models.BooleanField(default=False)),
                ('vtc_bool', models.BooleanField(default=False)),
                ('prot_perc', models.DecimalField(blank=True, decimal_places=2, default=0.35, max_digits=3)),
                ('carb_perc', models.DecimalField(blank=True, decimal_places=2, default=0.25, max_digits=3)),
                ('fat_perc', models.DecimalField(blank=True, decimal_places=2, default=0.4, max_digits=3)),
                ('stf_g_thr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fib_g_req', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sug_g_thr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sod_mg_thr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cho_mg_thr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clc_mg_req', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('irn_mg_req', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vta_mcg_req', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vtc_mg_req', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cal_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cal_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pro_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pro_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('car_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('car_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stf_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stf_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fib_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fib_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sug_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sug_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sod_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sod_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cho_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cho_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clc_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('clc_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('irn_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('irn_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vta_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vta_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('vtc_ub', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vtc_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('planner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannee', to='core.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], max_length=10)),
                ('dish_num', models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='Whole Meal', max_length=20)),
                ('prefmenu', models.ForeignKey(null=True, on_delete='CASCADE', to='core.PrefMenu')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Restaurants')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProbRejectFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.IntegerField(default=0)),
                ('removed', models.IntegerField(default=0)),
                ('dislike_ind', models.IntegerField(default=0)),
                ('last_view', models.DateField(default=datetime.date(2018, 1, 1))),
                ('max_servings', models.FloatField(default=4)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_pref_food', to='food.Foods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProbRejectMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.IntegerField(default=0)),
                ('removed', models.IntegerField(default=0)),
                ('dislike_ind', models.IntegerField(default=0)),
                ('last_view', models.DateField(default=datetime.date(2018, 1, 1))),
                ('max_servings', models.FloatField(default=2)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_pref_meal', to='plan.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mealtagpreferences',
            name='prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='core.PrefMenu'),
        ),
        migrations.AddField(
            model_name='mealtagpreferences',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.MealTags'),
        ),
        migrations.AddField(
            model_name='mealtagpreferences',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealpreferences',
            name='prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='core.PrefMenu'),
        ),
        migrations.AddField(
            model_name='mealpreferences',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodtagpreferences',
            name='prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='core.PrefMenu'),
        ),
        migrations.AddField(
            model_name='foodtagpreferences',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodTags'),
        ),
        migrations.AddField(
            model_name='foodtagpreferences',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodpreferences',
            name='prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='core.PrefMenu'),
        ),
        migrations.AddField(
            model_name='foodpreferences',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
