# Generated by Django 2.0 on 2019-08-19 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodtagpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mealpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mealtagpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurantpreferences',
            name='user',
        ),
        migrations.AddField(
            model_name='prefmenu',
            name='create_user',
            field=models.ForeignKey(default=5, on_delete='CASCADE', related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=1900, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=2100, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=143, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=158, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cho_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cho_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clc_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clc_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=74, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=82, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fib_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=25, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fib_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=45, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='irn_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=18, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='irn_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=45, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=119, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=131, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sod_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=500, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sod_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=2400, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stf_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stf_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sug_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sug_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vta_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vta_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vtc_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=90, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vtc_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userprobrejectfood',
            name='max_servings',
            field=models.FloatField(default=2),
        ),
    ]
