# Generated by Django 2.0 on 2019-11-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191115_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cal',
            field=models.BooleanField(default=True),
        ),
    ]
