# Generated by Django 2.0 on 2019-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprobrejectfood',
            name='default_dish_num',
            field=models.CharField(choices=[('side_1', 'side_1'), ('main', 'main'), ('side_2', 'side_2'), ('desert', 'desert'), ('snack', 'snack')], default='Whole Meal', max_length=20),
        ),
    ]
