# Generated by Django 2.0 on 2019-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191120_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=190, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='car_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=210, max_digits=6),
        ),
    ]
