# Generated by Django 2.0 on 2019-12-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191218_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprobrejectfood',
            name='max_num_per_week',
            field=models.FloatField(default=2),
        ),
    ]
