# Generated by Django 2.0 on 2020-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191221_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('info_source', models.URLField()),
            ],
        ),
    ]
