# Generated by Django 2.0 on 2020-01-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_nutrientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=300)),
                ('menu_description', models.TextField(null=True)),
                ('total_clones', models.IntegerField(default=0)),
                ('current_clones', models.IntegerField(default=0)),
                ('breakfast_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='public_br_prefmenu', to='core.PrefMenu')),
                ('create_user', models.ForeignKey(default=5, on_delete='CASCADE', related_name='public_menu_create_user', to=settings.AUTH_USER_MODEL)),
                ('dinner_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='public_di_prefmenu', to='core.PrefMenu')),
                ('lunch_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='public_lu_prefmenu', to='core.PrefMenu')),
                ('snack_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='public_sn_prefmenu', to='core.PrefMenu')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('foodtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MenuTags')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PublicMenu')),
            ],
        ),
        migrations.CreateModel(
            name='UserMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clone_date', models.DateField(null=True)),
                ('breakfast_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='user_br_prefmenu', to='core.PrefMenu')),
                ('cloned_from', models.ForeignKey(null=True, on_delete='SET_NULL', to='core.PublicMenu')),
                ('dinner_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='user_di_prefmenu', to='core.PrefMenu')),
                ('lunch_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='user_lu_prefmenu', to='core.PrefMenu')),
                ('snack_prefmenu', models.ForeignKey(on_delete='CASCADE', related_name='user_sn_prefmenu', to='core.PrefMenu')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='user_menu_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publicmenu',
            name='tags',
            field=models.ManyToManyField(through='core.TaggedMenus', to='core.MenuTags'),
        ),
    ]
