# Generated by Django 2.0 on 2020-01-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200118_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermenu',
            name='breakfast_prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_br_prefmenu', to='core.PrefMenu'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='dinner_prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_di_prefmenu', to='core.PrefMenu'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='lunch_prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_lu_prefmenu', to='core.PrefMenu'),
        ),
        migrations.AlterField(
            model_name='usermenu',
            name='snack_prefmenu',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='user_sn_prefmenu', to='core.PrefMenu'),
        ),
    ]
