# Generated by Django 2.0 on 2020-01-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200118_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='goals',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
