# Generated by Django 2.0 on 2020-01-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200121_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='current_weight_lbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='goal_weight_lbs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='max_menus',
            field=models.IntegerField(default=5),
        ),
    ]
