# Generated by Django 2.0 on 2020-02-26 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200129_1952'),
        ('core', '0019_auto_20200124_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbRejectCoefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=4)),
                ('viewed', models.FloatField(default=0)),
                ('removed', models.FloatField(default=0)),
                ('stars', models.FloatField(default=2.5)),
                ('total_uses', models.FloatField(default=0)),
                ('last_view', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_today_food', to='food.Foods')),
            ],
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='calories_reached_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='default_nuts_reached_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='macros_reached_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='plan_made_streak',
            field=models.IntegerField(default=0),
        ),
    ]
