# Generated by Django 2.0 on 2020-03-01 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userprobrejectmeal_user_total_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbRejectMealCoefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=4)),
                ('viewed', models.FloatField(default=0)),
                ('removed', models.FloatField(default=0)),
                ('total_uses', models.FloatField(default=0)),
                ('last_view', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProbRejectCoefficients',
            new_name='ProbRejectFoodCoefficients',
        ),
    ]
