# Generated by Django 2.0 on 2020-03-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprobrejectfood_last_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='probrejectfoodcoefficients',
            name='last_use',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='probrejectmealcoefficients',
            name='last_use',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='probrejectfoodcoefficients',
            name='stars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='probrejectmealcoefficients',
            name='last_view',
            field=models.FloatField(default=0),
        ),
    ]
