# Generated by Django 2.0 on 2020-03-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200301_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='probrejectcoefficients',
            name='days_since_use',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='probrejectcoefficients',
            name='days_since_view',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='probrejectcoefficients',
            name='inv_stars_mult',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='probrejectcoefficients',
            name='keep_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='probrejectcoefficients',
            name='random_var',
            field=models.FloatField(default=0),
        ),
    ]
