# Generated by Django 2.0 on 2020-03-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200301_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprobrejectmeal',
            name='user_star_rating',
            field=models.FloatField(default=2.5),
        ),
    ]
