# Generated by Django 2.0 on 2020-03-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='end_dt',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='start_dt',
        ),
    ]
