# Generated by Django 2.0 on 2020-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200324_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='always_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='status_end_date',
            field=models.DateField(null=True),
        ),
    ]
