# Generated by Django 2.0 on 2020-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200326_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='trial_start_date',
            field=models.DateField(null=True),
        ),
    ]
