# Generated by Django 2.0 on 2020-04-17 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_useraccount_stripe_sub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_dt', models.DateField(default=datetime.datetime.now)),
                ('message_type', models.CharField(choices=[('delete', 'delete'), ('bug', 'bug'), ('feature', 'feature'), ('data', 'data'), ('help', 'help'), ('other', 'other')], max_length=30)),
                ('message_text', models.TextField(null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
