# Generated by Django 2.0 on 2020-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_profile_first_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmenu',
            name='image_url',
            field=models.URLField(default='https://planyourmealsmedia.s3.amazonaws.com/menu/default_thumbnail.png'),
        ),
    ]
