# Generated by Django 2.0 on 2019-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprobrejectfood_default_dish_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddishes',
            name='dish',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodpreferences',
            name='dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodtagpreferences',
            name='dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealpreferences',
            name='dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealtagpreferences',
            name='dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantpreferences',
            name='dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprobrejectfood',
            name='default_dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
    ]
