# Generated by Django 2.0 on 2019-12-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191129_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='activity_lvl',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='height',
            new_name='height_feet',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inches',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
