# Generated by Django 2.0 on 2019-12-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191208_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_perc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.4, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fat_perc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.35, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_perc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.25, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprobrejectfood',
            name='max_servings',
            field=models.FloatField(default=4),
        ),
    ]
