# Generated by Django 2.0 on 2019-12-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprobrejectfood_max_num_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpreferences',
            name='max_num_per_week',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='foodpreferences',
            name='max_servings',
            field=models.FloatField(default=4),
        ),
    ]
