# Generated by Django 2.0 on 2019-12-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191219_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodpreferences',
            name='max_num_per_week',
        ),
        migrations.RemoveField(
            model_name='foodpreferences',
            name='max_servings',
        ),
    ]
