# Generated by Django 2.0 on 2019-12-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191219_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodfavorites',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodfavorites',
            name='user',
        ),
        migrations.AddField(
            model_name='globalprobrejectfood',
            name='global_star_rating',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='globalprobrejectfood',
            name='global_total_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprobrejectfood',
            name='user_star_rating',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='userprobrejectfood',
            name='user_total_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FoodFavorites',
        ),
    ]
