# Generated by Django 2.0 on 2020-01-18 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20200118_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(null=True)),
                ('bio', models.TextField(null=True)),
                ('avatar', models.URLField(null=True)),
                ('preferred_name', models.CharField(max_length=300)),
                ('goals', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='fooddishes',
            name='dish',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Main Courses', max_length=20),
        ),
    ]
