# Generated by Django 2.0 on 2020-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200226_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprobrejectmeal',
            name='user_total_uses',
            field=models.IntegerField(default=0),
        ),
    ]
