# Generated by Django 2.0 on 2020-03-01 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200301_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprobrejectfood',
            name='last_use',
            field=models.DateField(default=datetime.date(2018, 1, 1)),
        ),
    ]
