# Generated by Django 2.0 on 2020-03-01 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200301_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprobrejectmeal',
            name='last_use',
            field=models.DateField(default=datetime.date(2018, 1, 1)),
        ),
    ]
