# Generated by Django 2.0 on 2020-03-01 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userprobrejectmeal_last_use'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProbRejectMealCoefficients',
            new_name='ProbRejectCoefficients',
        ),
        migrations.DeleteModel(
            name='ProbRejectFoodCoefficients',
        ),
    ]
