# Generated by Django 2.0 on 2020-03-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200301_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probrejectcoefficients',
            name='last_use',
        ),
        migrations.RemoveField(
            model_name='probrejectcoefficients',
            name='last_view',
        ),
        migrations.RemoveField(
            model_name='probrejectcoefficients',
            name='removed',
        ),
        migrations.RemoveField(
            model_name='probrejectcoefficients',
            name='total_uses',
        ),
        migrations.RemoveField(
            model_name='probrejectcoefficients',
            name='viewed',
        ),
    ]
