# Generated by Django 2.0 on 2020-03-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprobrejectmeal_user_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='probrejectcoefficients',
            name='inv_total_uses',
            field=models.FloatField(default=0),
        ),
    ]
