# Generated by Django 2.0 on 2020-03-16 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_probrejectcoefficients_inv_total_uses'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_dt', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='trial', max_length=30)),
                ('start_dt', models.DateField(default=datetime.datetime.now)),
                ('end_dt', models.DateField(default=datetime.date(2020, 4, 15))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
