# Generated by Django 2.0 on 2020-03-22 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200322_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='stripe_cust_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='trial_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='trial_start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
