# Generated by Django 2.0 on 2020-03-24 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200322_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='trial_start_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
