# Generated by Django 2.0 on 2020-04-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200331_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='stripe_sub_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
