# Generated by Django 2.0 on 2020-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='delete_request_dt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='marketing_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='notification_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='requested_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='transactional_emails',
            field=models.BooleanField(default=True),
        ),
    ]
