# Generated by Django 2.0 on 2020-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200418_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status_start_date',
            field=models.DateField(null=True),
        ),
    ]
