# Generated by Django 2.0 on 2020-05-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_useraccount_status_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_session',
            field=models.BooleanField(default=True),
        ),
    ]
