# Generated by Django 2.0 on 2020-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_publicmenu_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nca_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=145, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='nca_req',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nca_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=165, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='nsu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nsu_lb',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='nsu_req',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nsu_ub',
            field=models.DecimalField(blank=True, decimal_places=2, default=45, max_digits=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cal_adj',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_unit',
            field=models.CharField(default='lb', max_length=2, null=True),
        ),
    ]
