# Generated by Django 2.0 on 2020-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200514_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('post', models.TextField()),
                ('title_image', models.URLField()),
                ('published', models.DateField()),
                ('embed_media', models.TextField()),
            ],
        ),
    ]
