# Generated by Django 2.0 on 2020-05-31 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='embed_media',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 10, 4, 37, 514632, tzinfo=utc)),
        ),
    ]
