# Generated by Django 2.0 on 2020-06-02 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200531_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='embed_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateField(default=datetime.datetime(2020, 6, 2, 21, 36, 28, 131624, tzinfo=utc)),
        ),
    ]
