# Generated by Django 2.0 on 2019-09-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20190923_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.URLField(blank=True, default='https://planyourmealsmedia.s3.amazonaws.com/food/default_thumbnail.png'),
        ),
    ]
