# Generated by Django 2.0 on 2019-11-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190929_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='default_dish_num',
            field=models.CharField(choices=[('Sides', 'Sides'), ('Main Courses', 'Main Courses'), ('Whole Meals', 'Whole Meals')], default='Whole Meal', max_length=20),
        ),
    ]
