# Generated by Django 2.0 on 2019-12-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foods_default_dish_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='max_num_per_week',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='foods',
            name='max_servings',
            field=models.FloatField(default=4),
        ),
    ]
