# Generated by Django 2.0 on 2019-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20191219_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedfoods',
            old_name='foods',
            new_name='food',
        ),
    ]
