# Generated by Django 2.0 on 2019-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_amount',
            name='unit',
        ),
        migrations.AddField(
            model_name='food_amount',
            name='serving_size_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food_amount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
