# Generated by Django 2.0 on 2019-10-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20191024_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_amount',
            old_name='amount',
            new_name='amt',
        ),
        migrations.RenameField(
            model_name='food_amount',
            old_name='serving_size_index',
            new_name='serving_size_idx',
        ),
    ]
