# Generated by Django 2.0 on 2020-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_mostrecentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=300, null=True)),
                ('embed_link', models.TextField()),
                ('episode_number', models.IntegerField()),
            ],
        ),
    ]
