# Generated by Django 5.1.5 on 2026-08-08 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("food_description", models.CharField(max_length=350, null=True)),
                ("brand", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "food_type_grp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("restaurant", "restaurant"),
                            ("grocery", "grocery"),
                            ("raw ingredient", "raw ingredient"),
                            ("recipe", "recipe"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("ingredients_list", models.TextField(blank=True, null=True)),
                ("serving_size_raw", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "serving_size_val",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("serving_size_unit", models.CharField(blank=True, max_length=200, null=True)),
                ("calories", models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ("protein_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("fat_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                (
                    "saturated_fat_g",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("carb_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("fiber_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("sugar_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("sodium_mg", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("cholesterol_mg", models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ("calcium_mg", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("iron_mg", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("vit_a_mcg", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("vit_c_mg", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("net_carb_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("net_sugar_g", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("image_url", models.URLField(blank=True, default="")),
                (
                    "default_dish_num",
                    models.CharField(
                        choices=[
                            ("Sides", "Sides"),
                            ("Main Courses", "Main Courses"),
                            ("Whole Meals", "Whole Meals"),
                        ],
                        default="Whole Meals",
                        max_length=20,
                    ),
                ),
                ("max_servings", models.FloatField(default=2)),
                ("max_num_per_week", models.FloatField(default=2)),
                ("star_rating", models.FloatField(default=2.5)),
                ("is_recipe", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_foods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "food_foods",
            },
        ),
        migrations.CreateModel(
            name="FoodTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
            ],
            options={
                "db_table": "food_foodtags",
            },
        ),
        migrations.CreateModel(
            name="FoodIndex",
            fields=[
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="food.food",
                    ),
                ),
                ("pro_index", models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ("fat_index", models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ("car_index", models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ("fib_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("clc_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("irn_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("vta_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("vtc_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("sug_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("stf_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("sod_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ("cho_index", models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                "db_table": "food_foodindex",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="recipe",
                        serialize=False,
                        to="food.food",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions", models.JSONField(default=list)),
                ("cook_time_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("prep_time_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("servings", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("image_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "food_recipes",
            },
        ),
        migrations.CreateModel(
            name="FoodTagMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.food"),
                ),
                (
                    "foodtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.foodtag"
                    ),
                ),
            ],
            options={
                "db_table": "food_taggedfoods",
            },
        ),
        migrations.AddField(
            model_name="food",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="food.FoodTagMapping", to="food.foodtag"
            ),
        ),
        migrations.CreateModel(
            name="RecipeFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ingred_food_desc", models.CharField(max_length=300)),
                ("ingred_amt", models.FloatField(default=1.0)),
                ("ingred_serving_size_unit", models.CharField(max_length=300)),
                (
                    "ingred_food",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_in_recipes",
                        to="food.food",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="food.recipe",
                    ),
                ),
            ],
            options={
                "db_table": "food_recipefood",
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["food_description"], name="food_description_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["is_recipe", "created_by"], name="food_recipe_creator_idx"),
        ),
    ]
