# Generated by Django 2.0 on 2019-08-08 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1.0)),
                ('unit', models.CharField(max_length=300, null=True)),
                ('amount_divisor', models.FloatField(null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='food.Foods')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mealname', models.CharField(default='Unnamed', max_length=300)),
                ('prep_time', models.CharField(blank=True, choices=[('long', 'long'), ('short', 'short'), ('none', 'none')], max_length=300, null=True)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Any', 'Any')], default='Any', max_length=300)),
                ('food_type_grp', models.CharField(choices=[('Restaurant', 'restaurant'), ('Grocery', 'grocery'), ('Recipe', 'recipe'), ('Raw Ingredient', 'raw ingredient'), ('Mixed', 'mixed')], default='Recipe', max_length=300)),
                ('saved', models.BooleanField(default=0)),
                ('cloned_n', models.IntegerField(default=1)),
                ('food', models.ManyToManyField(through='plan.Food_Amount', to='food.Foods')),
            ],
        ),
        migrations.CreateModel(
            name='MealTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(default='2019-01-01')),
                ('ml_cd', models.CharField(choices=[('br', 'br'), ('lu', 'lu'), ('di', 'di'), ('sn', 'sn')], default='di', max_length=2)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Dinner', max_length=20)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Meal')),
                ('meal_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_source', to='plan.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Meal')),
                ('mealtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.MealTags')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(through='plan.TaggedMeals', to='plan.MealTags'),
        ),
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food_amount',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Meal'),
        ),
        migrations.AlterUniqueTogether(
            name='taggedmeals',
            unique_together={('mealtag', 'meal')},
        ),
        migrations.AlterUniqueTogether(
            name='planmeal',
            unique_together={('user', 'meal_type', 'plan_date')},
        ),
    ]
