# Generated by Django 2.0 on 2019-10-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20191023_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_type_grp',
            field=models.CharField(choices=[('Restaurant', 'restaurant'), ('Grocery', 'grocery'), ('Recipe', 'recipe'), ('Raw Ingredient', 'raw ingredient'), ('Mixed', 'mixed')], default='Mixed', max_length=300),
        ),
    ]
