# Generated by Django 2.0 on 2020-01-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20191024_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('source', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
