# Generated by Django 5.1.5 on 2026-08-08 02:38

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrefMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("default_flg", models.BooleanField(default=False)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snack", "Snack"),
                            ("Any", "Any"),
                        ],
                        default="Any",
                        max_length=10,
                    ),
                ),
                ("menu_name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pref_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_prefmenu",
            },
        ),
        migrations.CreateModel(
            name="FoodPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snack", "Snack"),
                            ("Any", "Any"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dish_num",
                    models.CharField(
                        choices=[
                            ("Sides", "Sides"),
                            ("Main Courses", "Main Courses"),
                            ("Whole Meals", "Whole Meals"),
                        ],
                        default="Whole Meals",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="food.food"
                    ),
                ),
                (
                    "prefmenu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_preferences",
                        to="core.prefmenu",
                    ),
                ),
            ],
            options={
                "db_table": "core_foodpreferences",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")],
                        default="male",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(null=True)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ("weight_unit", models.CharField(default="lb", max_length=2, null=True)),
                ("height_feet", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("height_inches", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("activity", models.PositiveSmallIntegerField(default=1, null=True)),
                ("cal_adj", models.IntegerField(default=1, null=True)),
                ("bmr", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ("tdee", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ("cal", models.BooleanField(default=True)),
                ("pro", models.BooleanField(default=True)),
                ("car", models.BooleanField(default=True)),
                ("fat", models.BooleanField(default=True)),
                ("stf", models.BooleanField(default=False)),
                ("fib", models.BooleanField(default=False)),
                ("sug", models.BooleanField(default=False)),
                ("sod", models.BooleanField(default=False)),
                ("cho", models.BooleanField(default=False)),
                ("clc", models.BooleanField(default=False)),
                ("irn", models.BooleanField(default=False)),
                ("vta", models.BooleanField(default=False)),
                ("vtc", models.BooleanField(default=False)),
                ("nsu", models.BooleanField(default=False)),
                ("nca", models.BooleanField(default=False)),
                ("cal_req", models.DecimalField(decimal_places=2, default=2000, max_digits=7)),
                (
                    "pro_perc",
                    models.DecimalField(blank=True, decimal_places=2, default=0.25, max_digits=3),
                ),
                (
                    "car_perc",
                    models.DecimalField(blank=True, decimal_places=2, default=0.4, max_digits=3),
                ),
                (
                    "fat_perc",
                    models.DecimalField(blank=True, decimal_places=2, default=0.35, max_digits=3),
                ),
                (
                    "stf_thr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "fib_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "sug_thr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "sod_thr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "cho_thr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "clc_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "irn_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "vta_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "vtc_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "nsu_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "nca_req",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("cal_ub", models.DecimalField(decimal_places=2, default=2100, max_digits=6)),
                ("pro_ub", models.DecimalField(decimal_places=2, default=131, max_digits=6)),
                ("car_ub", models.DecimalField(decimal_places=2, default=210, max_digits=6)),
                ("fat_ub", models.DecimalField(decimal_places=2, default=82, max_digits=6)),
                ("stf_ub", models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ("fib_ub", models.DecimalField(decimal_places=2, default=45, max_digits=6)),
                ("sug_ub", models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ("sod_ub", models.DecimalField(decimal_places=2, default=2400, max_digits=6)),
                ("cho_ub", models.DecimalField(decimal_places=2, default=1000, max_digits=6)),
                ("clc_ub", models.DecimalField(decimal_places=2, default=2000, max_digits=7)),
                ("irn_ub", models.DecimalField(decimal_places=2, default=45, max_digits=6)),
                ("vta_ub", models.DecimalField(decimal_places=2, default=10000, max_digits=7)),
                ("vtc_ub", models.DecimalField(decimal_places=2, default=2000, max_digits=6)),
                ("nsu_ub", models.DecimalField(decimal_places=2, default=45, max_digits=6)),
                ("nca_ub", models.DecimalField(decimal_places=2, default=165, max_digits=6)),
                ("cal_lb", models.DecimalField(decimal_places=2, default=1900, max_digits=6)),
                ("pro_lb", models.DecimalField(decimal_places=2, default=119, max_digits=6)),
                ("car_lb", models.DecimalField(decimal_places=2, default=190, max_digits=6)),
                ("fat_lb", models.DecimalField(decimal_places=2, default=74, max_digits=6)),
                ("stf_lb", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("fib_lb", models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ("sug_lb", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("sod_lb", models.DecimalField(decimal_places=2, default=500, max_digits=6)),
                ("cho_lb", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("clc_lb", models.DecimalField(decimal_places=2, default=1000, max_digits=7)),
                ("irn_lb", models.DecimalField(decimal_places=2, default=18, max_digits=6)),
                ("vta_lb", models.DecimalField(decimal_places=2, default=5000, max_digits=7)),
                ("vtc_lb", models.DecimalField(decimal_places=2, default=90, max_digits=6)),
                ("nsu_lb", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("nca_lb", models.DecimalField(decimal_places=2, default=145, max_digits=6)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_profile",
            },
        ),
        migrations.CreateModel(
            name="PublicMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("menu_name", models.CharField(max_length=300)),
                ("menu_description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, default="")),
                ("total_clones", models.IntegerField(default=0)),
                ("current_clones", models.IntegerField(default=0)),
                (
                    "breakfast_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_br_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "create_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_menus_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dinner_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_di_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "lunch_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_lu_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "snack_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_sn_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
            ],
            options={
                "db_table": "core_publicmenu",
            },
        ),
        migrations.CreateModel(
            name="UserMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("clone_date", models.DateField(blank=True, null=True)),
                (
                    "breakfast_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_br_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.publicmenu",
                    ),
                ),
                (
                    "dinner_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_di_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "lunch_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_lu_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "snack_prefmenu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sn_prefmenu",
                        to="core.prefmenu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_menus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_usermenu",
            },
        ),
        migrations.CreateModel(
            name="UserProbRejectFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("viewed", models.IntegerField(default=0)),
                ("removed", models.IntegerField(default=0)),
                ("user_total_uses", models.IntegerField(default=0)),
                ("dislike_ind", models.IntegerField(default=0)),
                ("last_view", models.DateField(default=datetime.date(2018, 1, 1))),
                ("last_use", models.DateField(default=datetime.date(2018, 1, 1))),
                ("user_star_rating", models.FloatField(default=2.5)),
                ("max_servings", models.FloatField(default=4)),
                ("max_num_per_week", models.FloatField(default=2)),
                (
                    "default_dish_num",
                    models.CharField(
                        choices=[
                            ("Sides", "Sides"),
                            ("Main Courses", "Main Courses"),
                            ("Whole Meals", "Whole Meals"),
                        ],
                        default="Whole Meals",
                        max_length=20,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_prob_reject",
                        to="food.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_userprobrejectfood",
                "unique_together": {("food", "user")},
            },
        ),
    ]
