# Generated by Django 2.0 on 2019-08-08 12:42

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('food_key', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('food_description', models.CharField(max_length=350, null=True)),
                ('brand', models.CharField(max_length=250, null=True)),
                ('food_type_grp', models.CharField(choices=[('restaurant', 'restaurant'), ('grocery', 'grocery'), ('raw ingredient', 'raw ingredient'), ('recipe', 'recipe')], max_length=30, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('ingredients_list', models.TextField(null=True)),
                ('serving_size_raw', models.CharField(max_length=200, null=True)),
                ('serving_size_val', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('serving_size_unit', models.CharField(max_length=200, null=True)),
                ('calories', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('saturated_fat_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('carb_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fiber_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sugar_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cholesterol_mg', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('calcium_mg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('iron_mg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vit_a_mcg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vit_c_mg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingred_food_desc', models.CharField(max_length=300)),
                ('ingred_amt', models.FloatField(default=1.0)),
                ('ingred_serving_size_unit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('is_user', models.BooleanField(default=False)),
                ('source_url', models.URLField(null=True)),
                ('source_logo_img', models.ImageField(max_length=300, null=True, upload_to='uploads/recipe_source_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AltServingSize',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alt_serving_size', serialize=False, to='food.Foods')),
                ('serving_sizes', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodIndex',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='food.Foods')),
                ('pro_index', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('fat_index', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('car_index', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('fib_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('clc_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('irn_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('vta_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('vtc_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sug_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('stf_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sod_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('cho_index', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawIngredients',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='raw_ingredient', serialize=False, to='food.Foods')),
                ('food_description', models.CharField(max_length=350, unique=True)),
                ('cooked_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recipes', serialize=False, to='food.Foods')),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None)),
                ('cook_time', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('recipe_yield', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('num_ingred', models.IntegerField(null=True)),
                ('added_by', models.ForeignKey(on_delete=models.SET('deleted_user'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='taggedfoods',
            name='foods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Foods'),
        ),
        migrations.AddField(
            model_name='taggedfoods',
            name='foodtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodTags'),
        ),
        migrations.AddField(
            model_name='recipefood',
            name='ingred_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingred_food', to='food.Foods'),
        ),
        migrations.AddField(
            model_name='foods',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.Restaurants'),
        ),
        migrations.AddField(
            model_name='foods',
            name='tags',
            field=models.ManyToManyField(through='food.TaggedFoods', to='food.FoodTags'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredient',
            field=models.ManyToManyField(related_name='recipe_ingred_food', through='food.RecipeFood', to='food.Foods'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='source',
            field=models.ForeignKey(on_delete=models.SET('deleted_source'), to='food.RecipeSource'),
        ),
        migrations.AddField(
            model_name='recipefood',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_food', to='food.Recipes'),
        ),
        migrations.AlterUniqueTogether(
            name='rawingredients',
            unique_together={('food_description', 'cooked_flg')},
        ),
    ]
