# Generated by Django 2.0 on 2019-09-23 08:24

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190922_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=food.models.food_img_upload_path),
        ),
    ]
