# Generated by Django 2.0 on 2019-09-23 08:53

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20190923_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image_url',
            field=models.ImageField(blank=True, default='food_images/Default/thumbnail.png', upload_to=food.models.food_img_upload_path),
        ),
    ]
