# Generated by Django 2.0 on 2020-01-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20191221_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='max_servings',
            field=models.FloatField(default=2),
        ),
    ]
