# Generated by Django 2.0 on 2020-01-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200103_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='net_carb_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='net_sugar_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
