# Generated by Django 2.0 on 2020-03-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200129_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='star_rating',
            field=models.FloatField(default=2.5),
        ),
    ]
