# Generated by Django 2.0 on 2020-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_foods_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='wide_image_url',
            field=models.URLField(null=True),
        ),
    ]
