# Generated by Django 2.0 on 2020-03-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foods_wide_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_bad', models.BooleanField(default=False)),
                ('wide_bad', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image', to='food.Foods')),
            ],
        ),
    ]
