# Generated by Django 5.1.5 on 2026-08-08 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amt", models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ("serving_size_idx", models.IntegerField(default=0)),
                ("amount_divisor", models.FloatField(null=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_amounts",
                        to="food.food",
                    ),
                ),
            ],
            options={
                "db_table": "plan_food_amount",
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("mealname", models.CharField(default="Unnamed", max_length=300)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snack", "Snack"),
                            ("Any", "Any"),
                        ],
                        default="Any",
                        max_length=300,
                    ),
                ),
                ("saved", models.BooleanField(default=False)),
                ("food", models.ManyToManyField(through="plan.FoodAmount", to="food.food")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plan_meal",
            },
        ),
        migrations.AddField(
            model_name="foodamount",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_amounts",
                to="plan.meal",
            ),
        ),
        migrations.CreateModel(
            name="PlanMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("plan_date", models.DateField()),
                (
                    "ml_cd",
                    models.CharField(
                        choices=[("br", "br"), ("lu", "lu"), ("di", "di"), ("sn", "sn")],
                        default="di",
                        max_length=2,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("Snack", "Snack"),
                            ("Any", "Any"),
                        ],
                        default="Dinner",
                        max_length=20,
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_slots",
                        to="plan.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plan_planmeal",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "plan_date", "meal_type"), name="unique_user_date_mealtype"
                    )
                ],
            },
        ),
    ]
